#!/usr/bin/python3.7

import argparse
import logging

import cozmo
from readingtorobot.Cozmo import ReadEngine


if __name__ == "__main__":
    logging.basicConfig(format='%(asctime)s:%(levelname)s:\033[32m%(name)s\033[0m: %(message)s', level=logging.DEBUG)

    parser = argparse.ArgumentParser()
    parser.add_argument('-k', '--keyboard-control', action='store_true',
                        help="Trigger emotion animations manually using keyboard.")
    args = parser.parse_args()

    def cozmo_read_game(robot: cozmo.robot.Robot):
        # Initialize all the game engines screens and listners
        read_game = ReadEngine(robot, keyboard_control=args.keyboard_control)
        if read_game.tap_ready():
            if read_game.cozmo_setup_game():
                read_game.listen_to_story()

    cozmo.run_program(cozmo_read_game)
