#!/usr/bin/python2.7

from naoqi import ALProxy
import argparse
import logging
import sys
import time
import qi

from readingtorobot.NAO import RobotManager


if __name__ == "__main__":

    logging.basicConfig(format='%(asctime)s:%(levelname)s:\033[32m%(name)s\033[0m: %(message)s', level=logging.DEBUG)

    parser = argparse.ArgumentParser()
    parser.add_argument("--port", type=int,  default="9559",
                        help="Needed for connecting to virtual Choregraphe Nao")
    parser.add_argument("--robotIP", type=str,  default="127.0.0.1",
                        help="IP address of the robot, use 'localhost' for virtual Nao in" \
                        "Choregraphe")
    parser.add_argument("--mqttIP", type=str, default=None,
                        help="Ip of speech server.")
    parser.add_argument("--mov", type=str, default=None,
                        help="Robot movement: run, wave, choose-left -right -center, sad, happy")
    parser.add_argument('-k', '--keyboard-control', action='store_true',
                        help="Trigger emotion animations manually using keyboard.")

    args = parser.parse_args()

    motion = ALProxy("ALMotion", args.robotIP, args.port)

    try:
        # Initialize qi framework.
        connection_url = "tcp://" + args.robotIP + ":" + str(args.port)
        app = qi.Application(["HumanListener", "--qi-url=" + connection_url])
    except RuntimeError:
        print ("Can't connect to Naoqi at ip \"" + args.robotIP + "\" on port " + str(args.port) +".\n"
               "Please check your script arguments. Run with -h option for help.")
        sys.exit(1)

    motion.wakeUp()

    human_greeter = RobotManager(app,
                                 keyboard_control=args.keyboard_control,
                                 mqtt_ip=args.mqttIP)
    human_greeter.start()
    # Keep robot running
    try:
        while not human_greeter.done:
            time.sleep(1)
    except KeyboardInterrupt:
        print "\nInterrupted by user, shutting down"
        raise
    except BaseException, err:
        print err
        raise
    finally:
        human_greeter.stop()
        motion.rest()
        sys.exit(0)
